export const WEAR_REPOSITORY = 'WEAR_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES_REPOSITORY';
export const USERS_ROLES = 'USERS_ROLES_REPOSITORY';